### ISSUE TITLE
refactor: Implement GL functions in Renderer rather than Engine

### ISSUE THREAD

**Issue by ismayilovh** [coderloff/ferx#6]

**Comment by lindorffs** [comment]
You've got a good start here! Very impressive code, well organized, and it was easy to hop into modifying things.

https://github.com/lindorffs/ferx/commit/a839f5e682e818952008fb1086cb91f70de7cf94

**Comment by ismayilovh** [comment]
Thanks a lot for your kind words and great support. That's great to see contributors like you!

**Comment by lindorffs** [comment]
Implemented in commit 5fceafd.

**Comment by lindorffs** [comment]
You can remove even more calls related to rendering from the Engine Loop function `Engine::Run()` by including `UI.h` within `Renderer.cpp`  and calling `UI::Render(*s_Data.m_FBO);` after `FrameBuffer::Unbind();` in `Renderer::Render().`

Furthermore, by calling `glfwSwapBuffers()` at the end of `Renderer::Render()` as opposed to using `Renderer::End()` to call it, and moving `glfwPollEvents()` to the function `Engine::Run()`, you can eliminate all rendering related calls except the call to `Renderer::Render()` within the main loop.

Additionally, I would argue that the call to `glfwPollEvents()` should happen at the beginning of the loop, rather than the end. There's various reasons I have for this, with the main one being that it makes more logical sense to poll events before doing anything else, rather than doing everything else and then polling the events. When things evolve to include game logic, by polling events at the end of the frame, input for the "frame on screen" would be processed on the next frame. By polling events before rendering or updating the game logic, the input for the "frame on screen" has already been processed.

**Comment by ismayilovh** [comment]
> You can remove even more calls related to rendering from the Engine Loop function `Engine::Run()` by including `UI.h` within `Renderer.cpp`  and calling `UI::Render(*s_Data.m_FBO);` after `FrameBuffer::Unbind();` in `Renderer::Render().`
> 
> Furthermore, by calling `glfwSwapBuffers()` at the end of `Renderer::Render()` as opposed to using `Renderer::End()` to call it, and moving `glfwPollEvents()` to the function `Engine::Run()`, you can eliminate all rendering related calls except the call to `Renderer::Render()` within the main loop.
> 
> Additionally, I would argue that the call to `glfwPollEvents()` should happen at the beginning of the loop, rather than the end. There's various reasons I have for this, with the main one being that it makes more logical sense to poll events before doing anything else, rather than doing everything else and then polling the events. When things evolve to include game logic, by polling events at the end of the frame, input for the "frame on screen" would be processed on the next frame. By polling events before rendering or updating the game logic, the input for the "frame on screen" has already been processed.

This approach is actually much better and cleaner. I think I can get rid of this headache with this.

That makes sense; thanks a lot for the explanation! I'll try to make updates tomorrow.
